apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apoia-hpa
  namespace: negociais
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apoia
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80